name: m3circles
description: M3 Circle list viewer.

version: 2.0.1+1

environment:
  sdk: ">=2.5.0 <3.0.0"
  flutter: 1.9.1+hotfix.6

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  path_provider: ^1.4.0
  flutter_custom_tabs: ^0.6.0
  quiver: 2.0.5
  moor_flutter: # use the latest version

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: # use the latest version
  build_runner: 

flutter:
  uses-material-design: true

  assets:
    - assets/circles.json
